sudo: false

jobs:
  include:
    - stage: compile with gcc
      branches:
        except:
          - gh-pages
      language: cpp
      os: linux
      dist: xenial
      script: make reload compile example-js-compile
    - stage: compile with clang
      branches:
        except:
          - gh-pages
      language: cpp
      os: osx
      osx_image: xcode10.2
      script: make reload compile example-js-compile
    - stage: documentation
      language: bash
      branches:
        only:
          - master
      addons:
        apt:
          packages:
            - doxygen

      script:
        - doxygen Doxyfile
        - touch docs/html/.nojekyll

      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master