sudo: false

jobs:
  include:
    - stage: compile
      branches:
        except:
          - gh-pages
      language: cpp
      matrix:
        include:
          - os: osx
            osx_image: xcode10.2
          - os: linux
      script: make reload compile
    - stage: documentation
      language: bash
      branches:
        only:
          - master
      addons:
        apt:
          packages:
            - doxygen

      script:
        - doxygen Doxyfile
        - touch docs/html/.nojekyll

      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master