WHY_CPP: Text
Text
WHYCPP Public API
Functions to pri32 texts on the screen.
Classes
struct Glyph
class Font
Functions
void Print (Context &ctx, char ch, i32 x, i32 y, const RGBA &color, i32 size=1)
void Print (Context &ctx, const std::string &str, i32 x, i32 y, const RGBA &color, i32 size=1, i32 spacing=0)
Detailed Description
Functions to pri32 texts on the screen.
Function Documentation
void Print (Context & ctx, char ch, i32 x, i32 y, const RGBA & color, i32 size = 1)
Prints a single char at a position with color
Parameters
ctx
ch is a symbol to print
x
y
color
size
font
Definition at line 7 of file text.cpp.
References SetPixel().
Referenced by Print().
void Print (Context & ctx, const std::string & str, i32 x, i32 y, const RGBA & color, i32 size = 1, i32 spacing = 0)
Prints a string at a position with color
Parameters
ctx
str is a string to print
x
y
color
size
spacing is a distance between chars in the string
font
Definition at line 22 of file text.cpp.
References Print().