PALETTE_LEN: int = ...


def get_display_width() -> int: ...


def get_display_height() -> int: ...


def PALETTE(id: int) -> int: ...


def num_as_rgba(color: int) -> (int, int, int, int): ...


def rgba_as_num(red: int, green: int, blue: int, alpha: int) -> int: ...


def set_pixel(x: int, y: int, color: int) -> None: ...


def get_pixel(x: int, y: int) -> int: ...


def draw_clear_screen(color: int) -> None: ...


def draw_line(x0: int, y0: int, x1: int, y1: int, color: int) -> None: ...


def draw_rect_fill(x: int, y: int, w: int, h: int, color: int) -> None: ...


def draw_rect(x: int, y: int, w: int, h: int, color: int) -> None: ...


def draw_circle(x: int, y: int, radius: int, color: int) -> None: ...


def draw_circle_fill(x: int, y: int, radius: int, color: int) -> None: ...


def draw_sprite(sprite_id: int, screen_x: int, screen_y: int, sheet_x: int, sheet_y: int, width: int, height: int): ...


def get_delta() -> float: ...


def get_time() -> float: ...


def print(text: str, x: int, y: int, color: int, size: int, spacing: int) -> None: ...


def import_sprite(file_name: str) -> int: ...


def log_info(text: str) -> None: ...


def is_pressed(btn: int) -> bool: ...


def is_clicked(btn: int) -> bool: ...


def get_mouse() -> (int, int): ...


def exit() -> None: ...


KEY_A: int = ...
KEY_B: int = ...
KEY_C: int = ...
KEY_D: int = ...
KEY_E: int = ...
KEY_F: int = ...
KEY_G: int = ...
KEY_H: int = ...
KEY_I: int = ...
KEY_J: int = ...
KEY_K: int = ...
KEY_L: int = ...
KEY_M: int = ...
KEY_N: int = ...
KEY_O: int = ...
KEY_P: int = ...
KEY_Q: int = ...
KEY_R: int = ...
KEY_S: int = ...
KEY_T: int = ...
KEY_U: int = ...
KEY_V: int = ...
KEY_W: int = ...
KEY_X: int = ...
KEY_Y: int = ...
KEY_Z: int = ...
KEY_1: int = ...
KEY_2: int = ...
KEY_3: int = ...
KEY_4: int = ...
KEY_5: int = ...
KEY_6: int = ...
KEY_7: int = ...
KEY_8: int = ...
KEY_9: int = ...
KEY_0: int = ...
KEY_RETURN: int = ...
KEY_ESCAPE: int = ...
KEY_BACKSPACE: int = ...
KEY_TAB: int = ...
KEY_SPACE: int = ...
KEY_F1: int = ...
KEY_F2: int = ...
KEY_F3: int = ...
KEY_F4: int = ...
KEY_F5: int = ...
KEY_F6: int = ...
KEY_F7: int = ...
KEY_F8: int = ...
KEY_F9: int = ...
KEY_F10: int = ...
KEY_F11: int = ...
KEY_F12: int = ...
KEY_RIGHT: int = ...
KEY_LEFT: int = ...
KEY_DOWN: int = ...
KEY_UP: int = ...
KEY_LCTRL: int = ...
KEY_LSHIFT: int = ...
KEY_LALT: int = ...
KEY_RCTRL: int = ...
KEY_RSHIFT: int = ...
KEY_RALT: int = ...
MOUSE_BUTTON_LEFT: int = ...
MOUSE_BUTTON_MIDDLE: int = ...
MOUSE_BUTTON_RIGHT: int = ...
