#ifndef WHYCPP_ROOT_WHYCPP_PYTHON_SRC_WHYCPP_WRAPPER_H_
#define WHYCPP_ROOT_WHYCPP_PYTHON_SRC_WHYCPP_WRAPPER_H_

#include <Python.h>

PyObject *PyInit_whycpp(void);

#endif  // WHYCPP_ROOT_WHYCPP_PYTHON_SRC_WHYCPP_WRAPPER_H_
